#ifndef TOKENIZER_H
#define TOKENIZER_H

typedef enum {
    TOKEN_START_TAG,
    TOKEN_END_TAG,
    TOKEN_TEXT,
    TOKEN_COMMENT,
    TOKEN_EOF
} TokenType;

typedef enum{
    STATE_DATA,
    STATE_TAG_OPEN,
    STATE_END_TAG_OPEN,
    STATE_TAG_NAME,
    STATE_BEFORE_ATTRIBUTE_NAME,
    STATE_ATTRIBUTE_NAME,
    STATE_BEFORE_ATTRIBUTE_VALUE,
    STATE_ATTRIBUTE_VALUE_QUOTED,
    STATE_ATTRIBUTE_VALUE_UNQUOTED,
    STATE_MARKUP_DECLARETION,
    STATE_COMMENT,
    STATE_SELF_CLOSING_TAG
} TokenizerState;




#endif